### ISSUE TITLE
Twitter cards sometimes show a self.title()

### ISSUE THREAD

**Issue by fgregg** [datamade/bga-payroll#278]
https://twitter.com/JaredRutecki/status/1057265398935179264

![screenshot_2018-10-30 jared rutecki on twitter one of my favorite additions from the nerd-out dept go behind the curtain-ta](https://user-images.githubusercontent.com/536941/47724946-b007c500-dc25-11e8-98c7-78425ef914b0.png)

**Comment by hancush** [comment]
this righted itself.
