### ISSUE TITLE
Handle bad inputs for page

### ISSUE THREAD

**Issue by fgregg** [datamade/bga-payroll#317]
@hancush a little bit of QA for you.

(out of bounds)

https://bga-payroll.datamade.us/search/?name=chicago&salary_above=1500&entity_type=person&page=40

(page is not an integer)
https://bga-payroll.datamade.us/search/?name=chicago&salary_above=1500&entity_type=person&page=foo

(page is negative)
https://bga-payroll.datamade.us/search/?name=chicago&salary_above=1500&entity_type=person&page=-10

**Comment by hancush** [comment]
done in #318!
