### ISSUE TITLE
document solr setup

### ISSUE THREAD

**Issue by phjudge** [datamade/bga-payroll#334]
Solr dependency and setup instructions should be added to `README.md`.

This should be something along the lines of:
```bash
solr start
solr create -c bga -d ./solr_configs
```

**Comment by phjudge** [comment]
@hancush Is this right? I've never used solr before; I'm just guessing from `docker-compose.yml`.

**Comment by hancush** [comment]
that's right – if you're using a local solr install.

it's easier to use the dockerized version. provided you have docker installed on your computer, `docker-compose up solr` will start solr and create your core. n.b., you'll need to update your solr url to point to port 8986: https://github.com/datamade/bga-payroll/blob/5e6602d6985ab9bb7dc64b5020f37796b66d9fa2/bga_database/local_settings.py.example#L35.

**Comment by phjudge** [comment]
Are you also typically using the dockerized version for redis and postgres? And should we spell out docker usage in the README?

**Comment by hancush** [comment]
yes and yes. i probably won't get to this for a while, so i'd welcome a pr if you have the time to spare.

**Comment by phjudge** [comment]
I still need to add docker instructions to that PR, hence the draft status. I can take care of that, just won't be today.

**Comment by hancush** [comment]
perf! tyvm @phjudge.

**Comment by phjudge** [comment]
@hancush See the #335 (bettergov/bga-payroll#1 was set up to merge to BGA's fork, not datamade's)

**Comment by phjudge** [comment]
Closed in #335.
