### ISSUE TITLE
Remove payroll.context_processors.inspiration_slugs

### ISSUE THREAD

**Issue by phjudge** [datamade/bga-payroll#337]
An unused context processor,`payroll.context_processors.inspiration_slugs`, is getting loaded with every jinja2 template.

The query is super small, so limited impact on overhead... Nevertheless, it would make sense for this unused code to be phased out.

**Comment by phjudge** [comment]
I can include this in my cache revision PR, I just wanted to raise this here in case there was a good reason to keep it. @hancush?

**Comment by hancush** [comment]
the chicago slug gets used by the inspiration partial, which loads on every page iirc? https://github.com/datamade/bga-payroll/blob/master/templates/partials/inspiration.html

**Comment by phjudge** [comment]
You're right! I need to learn to cmd + f.
