### ISSUE TITLE
Update the Salary model to contain both base and extra pay

### ISSUE THREAD

**Issue by hancush** [datamade/bga-payroll#349]
Currently, the `Salary` model only contains an attribute for `amount`. 

https://github.com/datamade/bga-payroll/blob/1fd0a4bf6ce87ef79cc6a77cbc1f823fc5b8d5e7/payroll/models.py#L430-L445

Add an attribute for `extra_pay`. 

Previously, we omitted records without base pay, however there are now records without base pay but with extra pay that we want to retain. That means one or the other field can be null, but not both. Add a [check constraint](https://docs.djangoproject.com/en/3.0/ref/models/constraints/#checkconstraint) to the `Salary` model that prevents both fields from being null. See [this documentation on using Django `Q` objects to perform complex, i.e., compound, queries](https://docs.djangoproject.com/en/3.0/topics/db/queries/#complex-lookups-with-q-objects).

**Comment by fatima3558** [comment]
Addressed in #358
