### ISSUE TITLE
Implement pay breakout chart

### ISSUE THREAD

**Issue by hancush** [datamade/bga-payroll#366]
Using real data and HighCharts, write a pie chart to illustrate pay breakout. There will be two components to this: 

- [x] Generate the chart data in the view code and pass it in as template context
- [x] Write the HighCharts code to display the data as a chart

Here are some examples from Pensions:

- [Build data object to power a pie chart](https://github.com/datamade/bga-pensions/blob/8a484cbf6de9dbed3b1dc236317d4358bea20d32/pensions/views.py#L270)
- [Render the data as a HighChart](https://github.com/datamade/bga-pensions/blob/8a484cbf6de9dbed3b1dc236317d4358bea20d32/bga_database/static/js/base.js#L172)

**Comment by fatima3558** [comment]
Closed in #374
