### ISSUE TITLE
Multiple objects returned error

### ISSUE THREAD

**Issue by deraj1013** [datamade/bga-payroll#451]
This won't display the individual pages for employees. It [can be seen here](https://bga-payroll.datamade.us/person/dennis-reboletti-e4bc2e3e/), but it could be duplicated with almost any individual.

**Comment by deraj1013** [comment]
<img width="1435" alt="Screen Shot 2020-06-05 at 1 05 15 PM" src="https://user-images.githubusercontent.com/30843180/83908798-4f0f6f80-a72d-11ea-93de-79c3ed7f7a56.png">

**Comment by deraj1013** [comment]
This has manifested itself in a few ways. A good example can be seen with Barrington Hills. There are 53 employees, but when you search all employees, about 16 are not included. When you click on the names in the employee list, the same error message comes up.

**Comment by deraj1013** [comment]
This is much closer to correct. One other small thing ... it lists the correct number of employees now, but sometimes the employee list will have the 2017 salary, and then when you click through, it links to the 2018 pay information. This is a problem, but I'm unsure how major. 
<img width="765" alt="Screen Shot 2020-06-23 at 4 06 16 PM" src="https://user-images.githubusercontent.com/30843180/85463290-19abb400-b56c-11ea-8cc0-746ac3123825.png">
<img width="1128" alt="Screen Shot 2020-06-23 at 4 06 03 PM" src="https://user-images.githubusercontent.com/30843180/85463293-1a444a80-b56c-11ea-8492-b6f18af70f14.png">
<img width="1162" alt="Screen Shot 2020-06-23 at 4 05 50 PM" src="https://user-images.githubusercontent.com/30843180/85463295-1adce100-b56c-11ea-8d45-4b8e90a02038.png">

**Comment by hancush** [comment]
Good eye, @deraj1013 – opened a new issue (#456) for that.

**Comment by deraj1013** [comment]
Thank you ... didn't know if you wanted a new issue or not.
