### ISSUE TITLE
Year drop down hangup on older computer

### ISSUE THREAD

**Issue by deraj1013** [datamade/bga-payroll#475]
This may be an issue related to the user having a Stone Age computer, but they are reporting the text on the drop down menu getting stuck displaying the year 2018 in the data, even when the site has swapped to 2017 data. We couldn't duplicate the issue in Chrome or Safari, but the person was using Internet Explorer version 11.959.18362 on PC. 

In a nutshell, they select an employer. They come to the page and view 2018 data. They switch the year to 2017. The data switches to 2017, but the dropdown still reads 2018. Sometimes, it also changes to a C, which I imagine is a frozen version of the spinning wheel. 

This is a lower priority item, but worth looking into since you never can be sure what environment users are operating in.
![E269241573B442FE9271C4430AC75179](https://user-images.githubusercontent.com/30843180/89194363-df6f0280-d56c-11ea-9900-ce5ac9452b3e.png)

**Comment by hancush** [comment]
@deraj1013 Pushed a patch for this and tested on a VM running Windows/IE. Can you have this user confirm they're seeing the correct behavior?

**Comment by deraj1013** [comment]
I have messaged him, and I'll let you know as soon as I hear.

**Comment by deraj1013** [comment]
He says it's fixed on his end. Thank you!
