### ISSUE TITLE
Odd double in Park Forest Library

### ISSUE THREAD

**Issue by deraj1013** [datamade/bga-payroll#476]
My raw data doesn't have duplicate data, but when I look at Park Forest Library District, every employee is there twice. 

https://bga-payroll.datamade.us/unit/park-forest-library-district-8e8ab9c8/?data_year=2018

<img width="1143" alt="Screen Shot 2020-08-04 at 5 37 20 PM" src="https://user-images.githubusercontent.com/30843180/89352229-437eed00-d679-11ea-82cd-7193deb3b82e.png">

**Comment by hancush** [comment]
Great catches, @deraj1013! Like #477, it looks like this appears in the version of the 2018 data I have. Here's this excerpt: https://docs.google.com/spreadsheets/d/1XMEXcnISLmadkamt6Er2Bw3kaFa6PKxl9EP-l2Qlq3A/edit?usp=sharing.

Definitely send me the latest 2018 data, and we'll double check these once I reupload to confirm it resolves the problem.
