### ISSUE TITLE
Add BGA story feed

### ISSUE THREAD

**Issue by hancush** [datamade/bga-payroll#482]
Add story feed sourced from a bettergov.org RSS feed to the right rail of the Salaries database.

**Comment by hancush** [comment]
Draft of this is live on the staging site. One hiccup is that the lead image link isn't in the RSS feed, so I pivoted and displayed the headline and summary, instead. @deraj1013, can you have a look and let me know if it looks ok?

**Comment by deraj1013** [comment]
It looks ok to me. There is one oddball thing with that story ... the image for that first story is massive. I'm wondering if 1). we could force this info into the RSS feed, and 2). if it would only be a problem with this current story. I'll check on the other things and get back to you, but I think for now, this is a safe compromise.

**Comment by hancush** [comment]
Link "From the newsroom" to bettergov.org
