### ISSUE TITLE
The search index is missing people

### ISSUE THREAD

**Issue by hancush** [datamade/bga-payroll#539]
Per @deraj1013:

> One thing I've seen a couple times is people not showing up in search that are definitely in the data. I'll be able to find them in the department, or by scrolling, but search misses them. Last one to do it is this person from City Colleges of Chicago. I have to turn it on 2018 to find their 2019 data. 

<img width="1243" alt="Screen Shot 2021-09-02 at 2 22 07 PM" src="https://user-images.githubusercontent.com/12176173/131905163-4c165188-3fb8-4e2b-90a0-2a7b37502b24.png">
<img width="1267" alt="Screen Shot 2021-09-02 at 2 21 57 PM" src="https://user-images.githubusercontent.com/12176173/131905174-55766da2-d400-4b83-975c-0e10a8a42e2d.png">

**Comment by deraj1013** [comment]
Duplicated it here, too...   
<img width="851" alt="Screen Shot 2021-09-02 at 3 28 24 PM" src="https://user-images.githubusercontent.com/30843180/131920396-3f91242f-92ca-4578-abe7-1bb768fb37e1.png">

**Comment by deraj1013** [comment]
The entire list of individuals for Crestwood Library District doesn't show up when I click on the view all employees tab for the employer. I also cannot find employees when I search for them from the main search bar without employees.

**Comment by hancush** [comment]
@deraj1013 I am rebuilding the person search index to address the core issue. Will update you when it's done.

**Comment by hancush** [comment]
@deraj1013 2019 person index rebuilt. Hark!

- Henry C. Allen: https://bga-payroll.datamade.us/search/?entity_type=person&name=henry%20c%20allen
- Iwona Pipikios: https://bga-payroll.datamade.us/search/?entity_type=person&name=iwona%20pipikios
- Crestwood Library District: https://bga-payroll.datamade.us/search/?entity_type=person&employer=crestwood-library-district-46712f87&year=2019

Teeing off 2017/2018 reindex now, but the new data should all be present.

**Comment by deraj1013** [comment]
Sounds great - thank you!

**Comment by hancush** [comment]
2018 is up! Just kicked off 2017. Will circle back on Tuesday to confirm all is well. Meanwhile, have a great holiday weekend, @deraj1013.

**Comment by deraj1013** [comment]
Looks like this fixed the search on our end - thanks a lot
