### ISSUE TITLE
Update the user Q&A

### ISSUE THREAD

**Issue by deraj1013** [datamade/bga-payroll#557]
We are going to have a slight update on the Q&A for this year. Let us know when you are ready to update it and we will approve - John and I are finalizing a two small things, and when we clear out of there, this will be ready.

The language lives here: https://docs.google.com/document/d/1bOWtMhfMW-jjzkrM6_vbhnvUeq7DU0jTyYs8DQpSPjU/edit?usp=sharing

**Comment by deraj1013** [comment]
This can be updated now - please let me know if you have any questions. https://bga-payroll.datamade.us/user-guide/

**Comment by fgregg** [comment]
thanks! we are on it @deraj1013!
