### ISSUE TITLE
Unit/department not populated correctly when downloading data from unit page

### ISSUE THREAD

**Issue by hancush** [datamade/bga-payroll#564]
Replicated for a couple of units:

[Cook County](https://bga-payroll.datamade.us/unit/cook-county-5370fcc1/?data_year=2019)

<img width="830" alt="Screen Shot 2021-11-16 at 8 18 12 AM" src="https://user-images.githubusercontent.com/12176173/142002014-d14b2371-f1c0-4303-816c-3da26d5d874e.png">

[Cook County SD 130](https://bga-payroll.datamade.us/unit/cook-county-sd-130-13584792/?data_year=2019)

<img width="852" alt="Screen Shot 2021-11-16 at 8 17 49 AM" src="https://user-images.githubusercontent.com/12176173/142002025-e9de7961-b1aa-434f-9931-422def728d7f.png">

Downloading data from the department page seems to behave correctly (unit in unit column, department in department column).

**Comment by fgregg** [comment]
What is the expected behavior for top level units

| name | unit | department |
|-|-|-|
| Karina, Alatorre | Cook County SD 130 | Cook County SD 130 |

or 

| name | unit | department |
|-|-|-|
| Karina, Alatorre | Cook County SD 130 |  |

**Comment by hancush** [comment]
SD was a bad example because it doesn't have departments. This is more a problem for units like Cook County, which _does_ have departments, which are not reflected in the export.

For units with departments:

| name | unit | department | 
|-|-|-|
| Name | Cook County | e.g., Stroger Hospital Of Cook Cnty |

For direct employees of a unit:

| name | unit | department |
|-|-|-|
| Karina, Alatorre | Cook County SD 130 |  |

**Comment by fgregg** [comment]
okay, thanks!
