### ISSUE TITLE
Style standardized data download link

### ISSUE THREAD

**Issue by hancush** [datamade/bga-payroll#565]
Right now, the data download link blends in with the search link. Would it be possible to pull it right and perhaps make it a more distinctive button? Rough sketch (styles flexible):

<img width="849" alt="Screen Shot 2021-11-16 at 8 20 06 AM" src="https://user-images.githubusercontent.com/12176173/142002752-5f2bbe38-0987-412d-b4ee-36c56495e7a1.png">

**Comment by smcalilly** [comment]
@hancush how did you do that CSS so the element is aligned right? your screenshot looks so easy but i'm having to re-do the markup and feels like i'm doing it wrong.

**Comment by hancush** [comment]
@smcalilly I drew it on in Preview 😅

In the past, I've used [a Bootstrap class called `float-right`](https://getbootstrap.com/docs/4.0/utilities/float/#classes).
